import type { RecipeDefinition, StateDefinition } from "@sweny-ai/engine";

/**
 * Convert a kebab-case, snake_case, or space-separated string to camelCase.
 * Also strips any characters that are not valid in JS identifiers.
 */
function toCamelCase(str: string): string {
  // Replace separators (hyphens, underscores, spaces) with a split marker, then capitalize
  const camel = str
    .replace(/[^a-zA-Z0-9_\- ]/g, "") // strip invalid chars except separators
    .replace(/[-_ ]+(.)/g, (_, ch: string) => ch.toUpperCase())
    .replace(/^[^a-zA-Z_$]/, "_"); // ensure starts with valid identifier char
  return camel;
}

/**
 * Return true if a key is a valid JS identifier (no quotes needed).
 */
function isValidIdentifier(key: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

/**
 * Format an object key for a TypeScript object literal.
 * Simple identifiers are unquoted; anything else is JSON-encoded (handles
 * embedded quotes, backslashes, and other special characters correctly).
 */
function formatKey(key: string): string {
  return isValidIdentifier(key) ? key : JSON.stringify(key);
}

/**
 * Serialize a StateDefinition as indented TypeScript object literal lines.
 * Produces multi-line format for `on` maps, single-line for simple states.
 */
function serializeState(state: StateDefinition, indent: string): string {
  const inner = `${indent}  `;
  const lines: string[] = ["{"];

  // JSON.stringify produces a correctly escaped TS string literal (handles \n, \t, \, ", etc.)
  lines.push(`${inner}phase: ${JSON.stringify(state.phase)},`);

  if (state.description !== undefined) {
    lines.push(`${inner}description: ${JSON.stringify(state.description)},`);
  }

  if (state.critical === true) {
    lines.push(`${inner}critical: true,`);
  }

  if (state.next !== undefined) {
    lines.push(`${inner}next: ${JSON.stringify(state.next)},`);
  }

  if (state.on !== undefined) {
    const onEntries = Object.entries(state.on);
    if (onEntries.length === 0) {
      lines.push(`${inner}on: {},`);
    } else if (onEntries.length === 1) {
      const [k, v] = onEntries[0];
      lines.push(`${inner}on: { ${formatKey(k)}: ${JSON.stringify(v)} },`);
    } else {
      lines.push(`${inner}on: {`);
      for (const [k, v] of onEntries) {
        lines.push(`${inner}  ${formatKey(k)}: ${JSON.stringify(v)},`);
      }
      lines.push(`${inner}},`);
    }
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Serialize the full RecipeDefinition as a TypeScript const expression.
 */
function serializeDefinition(def: RecipeDefinition, constName: string): string {
  const lines: string[] = [];
  lines.push(`export const ${constName}Definition: RecipeDefinition = {`);
  lines.push(`  id: ${JSON.stringify(def.id)},`);
  lines.push(`  version: ${JSON.stringify(def.version)},`);
  lines.push(`  name: ${JSON.stringify(def.name)},`);

  if (def.description !== undefined) {
    lines.push(`  description: ${JSON.stringify(def.description)},`);
  }

  lines.push(`  initial: ${JSON.stringify(def.initial)},`);
  lines.push(`  states: {`);

  for (const [stateId, stateDef] of Object.entries(def.states)) {
    const key = formatKey(stateId);
    const serialized = serializeState(stateDef, "    ");
    lines.push(`    ${key}: ${serialized},`);
  }

  lines.push(`  },`);
  lines.push(`};`);

  return lines.join("\n");
}

/**
 * Build the outcome comment for a state: lists all on: transitions and next,
 * skipping "end" targets since it's a built-in terminal state.
 */
function buildOutcomeComment(state: StateDefinition): string {
  const parts: string[] = [];

  if (state.on !== undefined) {
    for (const [outcome, target] of Object.entries(state.on)) {
      if (target !== "end") {
        parts.push(`${outcome} → ${target}`);
      } else {
        parts.push(`${outcome} → end`);
      }
    }
  }

  if (state.next !== undefined) {
    const label = state.next === "end" ? "(default) → end" : `(default) → ${state.next}`;
    parts.push(label);
  }

  if (parts.length === 0) {
    return "// Outcomes: (terminal)";
  }

  return `// Outcomes: ${parts.join(" | ")}`;
}

/**
 * Generate a TypeScript recipe file from a RecipeDefinition.
 * Output is ready to drop into a Node.js project that has @sweny-ai/engine installed.
 */
export function exportAsTypescript(definition: RecipeDefinition): string {
  const camelName = toCamelCase(definition.id);
  // Capitalize first letter for the variable name prefix (e.g. myFlow → MyFlow not needed, keep lower)
  const varName = camelName.length > 0 ? camelName : "recipe";

  const stateEntries = Object.entries(definition.states);

  // Build header comment
  const header = [
    `/**`,
    ` * ${definition.name} — generated by sweny studio`,
    ` * Recipe ID: ${definition.id} | Version: ${definition.version}`,
    ` */`,
  ].join("\n");

  // Imports
  const imports = [
    `import { createRecipe } from "@sweny-ai/engine";`,
    `import type { RecipeDefinition, WorkflowContext, StepResult } from "@sweny-ai/engine";`,
  ].join("\n");

  // Definition const
  const defBlock = serializeDefinition(definition, varName);

  // Implementation stubs separator
  const implHeader = [
    `// ${"─".repeat(3)} Implementations ${"─".repeat(67 - "Implementations".length)}`,
    `// Return { status: "success" | "skipped" | "failed", data?: { outcome?: string } }`,
    `// Use data.outcome to drive named on: transitions.`,
  ].join("\n");

  // Generate one async function per state
  const stubs = stateEntries.map(([stateId, stateDef]) => {
    const fnName = toCamelCase(stateId);
    const outcomeComment = buildOutcomeComment(stateDef);
    return [
      `async function ${fnName}(ctx: WorkflowContext<unknown>): Promise<StepResult> {`,
      `  ${outcomeComment}`,
      `  void ctx;`,
      `  return { status: "success" };`,
      `}`,
    ].join("\n");
  });

  // Recipe call separator + createRecipe call
  const recipeHeader = `// ${"─".repeat(3)} Recipe ${"─".repeat(75 - "Recipe".length)}`;

  const implMap = stateEntries
    .map(([stateId]) => {
      const fnName = toCamelCase(stateId);
      const key = formatKey(stateId);
      return `  ${key}: ${fnName},`;
    })
    .join("\n");

  const recipeCall = [`export const ${varName}Recipe = createRecipe(${varName}Definition, {`, implMap, `});`].join(
    "\n",
  );

  return [header, imports, defBlock, implHeader, ...stubs, recipeHeader, recipeCall].join("\n\n");
}
