import type { WorkflowDefinition, StepDefinition } from "@sweny-ai/engine";

/**
 * Convert a kebab-case, snake_case, or space-separated string to camelCase.
 * Also strips any characters that are not valid in JS identifiers.
 */
function toCamelCase(str: string): string {
  // Replace separators (hyphens, underscores, spaces) with a split marker, then capitalize
  const camel = str
    .replace(/[^a-zA-Z0-9_\- ]/g, "") // strip invalid chars except separators
    .replace(/[-_ ]+(.)/g, (_, ch: string) => ch.toUpperCase())
    .replace(/^[^a-zA-Z_$]/, "_"); // ensure starts with valid identifier char
  return camel;
}

/**
 * Return true if a key is a valid JS identifier (no quotes needed).
 */
function isValidIdentifier(key: string): boolean {
  return /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key);
}

/**
 * Format an object key for a TypeScript object literal.
 * Simple identifiers are unquoted; anything else is JSON-encoded (handles
 * embedded quotes, backslashes, and other special characters correctly).
 */
function formatKey(key: string): string {
  return isValidIdentifier(key) ? key : JSON.stringify(key);
}

/**
 * Serialize a StepDefinition as indented TypeScript object literal lines.
 * Produces multi-line format for `on` maps, single-line for simple steps.
 */
function serializeStep(step: StepDefinition, indent: string): string {
  const inner = `${indent}  `;
  const lines: string[] = ["{"];

  // JSON.stringify produces a correctly escaped TS string literal (handles \n, \t, \, ", etc.)
  lines.push(`${inner}phase: ${JSON.stringify(step.phase)},`);

  if (step.description !== undefined) {
    lines.push(`${inner}description: ${JSON.stringify(step.description)},`);
  }

  if (step.critical === true) {
    lines.push(`${inner}critical: true,`);
  }

  if (step.next !== undefined) {
    lines.push(`${inner}next: ${JSON.stringify(step.next)},`);
  }

  if (step.on !== undefined) {
    const onEntries = Object.entries(step.on);
    if (onEntries.length === 0) {
      lines.push(`${inner}on: {},`);
    } else if (onEntries.length === 1) {
      const [k, v] = onEntries[0];
      lines.push(`${inner}on: { ${formatKey(k)}: ${JSON.stringify(v)} },`);
    } else {
      lines.push(`${inner}on: {`);
      for (const [k, v] of onEntries) {
        lines.push(`${inner}  ${formatKey(k)}: ${JSON.stringify(v)},`);
      }
      lines.push(`${inner}},`);
    }
  }

  lines.push(`${indent}}`);
  return lines.join("\n");
}

/**
 * Serialize the full WorkflowDefinition as a TypeScript const expression.
 */
function serializeDefinition(def: WorkflowDefinition, constName: string): string {
  const lines: string[] = [];
  lines.push(`export const ${constName}Definition: WorkflowDefinition = {`);
  lines.push(`  id: ${JSON.stringify(def.id)},`);
  lines.push(`  version: ${JSON.stringify(def.version)},`);
  lines.push(`  name: ${JSON.stringify(def.name)},`);

  if (def.description !== undefined) {
    lines.push(`  description: ${JSON.stringify(def.description)},`);
  }

  lines.push(`  initial: ${JSON.stringify(def.initial)},`);
  lines.push(`  steps: {`);

  for (const [stepId, stepDef] of Object.entries(def.steps)) {
    const key = formatKey(stepId);
    const serialized = serializeStep(stepDef, "    ");
    lines.push(`    ${key}: ${serialized},`);
  }

  lines.push(`  },`);
  lines.push(`};`);

  return lines.join("\n");
}

/**
 * Build the outcome comment for a step: lists all on: transitions and next,
 * skipping "end" targets since it's a built-in terminal state.
 */
function buildOutcomeComment(step: StepDefinition): string {
  const parts: string[] = [];

  if (step.on !== undefined) {
    for (const [outcome, target] of Object.entries(step.on)) {
      if (target !== "end") {
        parts.push(`${outcome} → ${target}`);
      } else {
        parts.push(`${outcome} → end`);
      }
    }
  }

  if (step.next !== undefined) {
    const label = step.next === "end" ? "(default) → end" : `(default) → ${step.next}`;
    parts.push(label);
  }

  if (parts.length === 0) {
    return "// Outcomes: (terminal)";
  }

  return `// Outcomes: ${parts.join(" | ")}`;
}

/**
 * Generate a TypeScript workflow file from a WorkflowDefinition.
 * Output is ready to drop into a Node.js project that has @sweny-ai/engine installed.
 */
export function exportAsTypescript(definition: WorkflowDefinition): string {
  const camelName = toCamelCase(definition.id);
  const varName = camelName.length > 0 ? camelName : "workflow";

  const stepEntries = Object.entries(definition.steps);

  // Build header comment
  const header = [
    `/**`,
    ` * ${definition.name} — generated by sweny studio`,
    ` * Workflow ID: ${definition.id} | Version: ${definition.version}`,
    ` */`,
  ].join("\n");

  // Imports
  const imports = [
    `import { createWorkflow } from "@sweny-ai/engine";`,
    `import type { WorkflowDefinition, WorkflowContext, StepResult } from "@sweny-ai/engine";`,
  ].join("\n");

  // Definition const
  const defBlock = serializeDefinition(definition, varName);

  // Implementation stubs separator
  const implHeader = [
    `// ${"─".repeat(3)} Implementations ${"─".repeat(67 - "Implementations".length)}`,
    `// Return { status: "success" | "skipped" | "failed", data?: { outcome?: string } }`,
    `// Use data.outcome to drive named on: transitions.`,
  ].join("\n");

  // Generate one async function per step
  const stubs = stepEntries.map(([stepId, stepDef]) => {
    const fnName = toCamelCase(stepId);
    const outcomeComment = buildOutcomeComment(stepDef);
    return [
      `async function ${fnName}(ctx: WorkflowContext<unknown>): Promise<StepResult> {`,
      `  ${outcomeComment}`,
      `  void ctx;`,
      `  return { status: "success" };`,
      `}`,
    ].join("\n");
  });

  // Workflow call separator + createWorkflow call
  const workflowHeader = `// ${"─".repeat(3)} Workflow ${"─".repeat(75 - "Workflow".length)}`;

  const implMap = stepEntries
    .map(([stepId]) => {
      const fnName = toCamelCase(stepId);
      const key = formatKey(stepId);
      return `  ${key}: ${fnName},`;
    })
    .join("\n");

  const workflowCall = [
    `export const ${varName}Workflow = createWorkflow(${varName}Definition, {`,
    implMap,
    `});`,
  ].join("\n");

  return [header, imports, defBlock, implHeader, ...stubs, workflowHeader, workflowCall].join("\n\n");
}
