import type { WorkflowDefinition } from "@sweny-ai/engine";

/**
 * Collect the set of provider roles used by any step in the workflow.
 * Based on the step's `uses` field (set by the Studio type selector).
 */
function collectProviderRoles(definition: WorkflowDefinition): Set<string> {
  const roles = new Set<string>();
  for (const step of Object.values(definition.steps)) {
    for (const role of step.uses ?? []) {
      roles.add(role);
    }
  }
  return roles;
}

/**
 * Build the env block and comment block for the GHA workflow based on
 * which provider roles are actually used.
 */
function buildEnvBlock(roles: Set<string>): string {
  const lines: string[] = [];

  // Coding agent — always needed if `codingAgent` role is present
  if (roles.has("codingAgent")) {
    lines.push("          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}");
  }

  // GitHub token — needed for issueTracker (github-issues) or sourceControl (github)
  if (roles.has("issueTracker") || roles.has("sourceControl")) {
    lines.push("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}");
  }

  // Observability providers — include comments for all common options
  if (roles.has("observability")) {
    lines.push("          # Observability — uncomment the block for your provider:");
    lines.push("          # Datadog:");
    lines.push("          # DD_API_KEY: ${{ secrets.DD_API_KEY }}");
    lines.push("          # DD_APP_KEY: ${{ secrets.DD_APP_KEY }}");
    lines.push("          # Sentry:");
    lines.push("          # SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}");
  }

  // Linear issue tracker
  if (roles.has("issueTracker")) {
    lines.push("          # Issue tracker — uncomment if using Linear:");
    lines.push("          # LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}");
    lines.push("          # LINEAR_TEAM_ID: ${{ secrets.LINEAR_TEAM_ID }}");
  }

  // Notification
  if (roles.has("notification")) {
    lines.push("          # Notification — uncomment for your provider:");
    lines.push("          # NOTIFICATION_WEBHOOK_URL: ${{ secrets.NOTIFICATION_WEBHOOK_URL }}");
  }

  if (lines.length === 0) {
    lines.push("          # No provider secrets needed for file-based providers");
  }

  return lines.join("\n");
}

/**
 * Generate a ready-to-commit GitHub Actions workflow YAML that runs
 * `sweny triage` on a daily schedule with appropriate secrets configured
 * based on the step types in the workflow definition.
 */
export function exportAsGitHubActions(definition: WorkflowDefinition): string {
  const roles = collectProviderRoles(definition);
  const envBlock = buildEnvBlock(roles);

  return `# Generated by SWEny Studio — https://github.com/swenyai/sweny
# Workflow: ${definition.name} (${definition.id})
name: "SWEny — ${definition.name}"

on:
  schedule:
    - cron: "0 6 * * *"  # Daily at 06:00 UTC — adjust as needed
  workflow_dispatch:       # Manual trigger via GitHub Actions UI

jobs:
  sweny:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Create branches and commit code
      pull-requests: write  # Open pull requests
      issues: write         # Create and comment on issues

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install SWEny CLI
        run: npm install -g @sweny-ai/cli

      - name: Run SWEny triage
        env:
${envBlock}
        run: sweny triage
`;
}
