import type { Workflow } from "@sweny-ai/core";

/**
 * Collect the set of skill IDs used by any node in the workflow.
 */
function collectSkills(workflow: Workflow): Set<string> {
  const skills = new Set<string>();
  for (const node of Object.values(workflow.nodes)) {
    for (const skillId of node.skills) {
      skills.add(skillId);
    }
  }
  return skills;
}

/**
 * Build the env block for the GHA workflow based on which skills are used.
 */
function buildEnvBlock(skills: Set<string>): string {
  const lines: string[] = [];

  if (skills.has("github")) {
    lines.push("          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}");
  }

  if (skills.has("linear")) {
    lines.push("          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}");
  }

  if (skills.has("sentry")) {
    lines.push("          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}");
    lines.push("          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}");
  }

  if (skills.has("datadog")) {
    lines.push("          DD_API_KEY: ${{ secrets.DD_API_KEY }}");
    lines.push("          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}");
  }

  if (skills.has("slack")) {
    lines.push("          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}");
  }

  if (skills.has("notification")) {
    lines.push("          NOTIFICATION_WEBHOOK_URL: ${{ secrets.NOTIFICATION_WEBHOOK_URL }}");
  }

  // Always include Anthropic key for Claude
  lines.push("          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}");

  return lines.join("\n");
}

/**
 * Generate a GitHub Actions workflow YAML that runs this SWEny workflow.
 */
export function exportAsGitHubActions(workflow: Workflow): string {
  const skills = collectSkills(workflow);
  const envBlock = buildEnvBlock(skills);

  return `# Generated by SWEny Studio — https://github.com/swenyai/sweny
# Workflow: ${workflow.name} (${workflow.id})
name: "SWEny — ${workflow.name}"

on:
  schedule:
    - cron: "0 6 * * *"  # Daily at 06:00 UTC — adjust as needed
  workflow_dispatch:       # Manual trigger via GitHub Actions UI

jobs:
  sweny:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install SWEny CLI
        run: npm install -g @sweny-ai/cli

      - name: Run SWEny workflow
        env:
${envBlock}
        run: sweny run ${workflow.id}
`;
}
