#!/bin/bash
# Verify a sweny-worker Docker image was built from a specific git commit.
#
# Usage:
#   ./verify-build.sh <image> <commit>
#
# Example:
#   ./verify-build.sh swenyai/worker:v1.2.3 abc1234
#
# This script:
#   1. Pulls the image manifest and extracts its SHA256 digest
#   2. Prints the digest and the expected commit for manual cross-reference
#   3. Points you to the GitHub Releases attestation where the canonical mapping is published
#
# For automated verification, compare the digest against the attestation JSON
# published at https://github.com/swenyai/sweny/releases/tag/worker-<commit>

set -euo pipefail

IMAGE=${1:-}
COMMIT=${2:-}

if [[ -z "$IMAGE" || -z "$COMMIT" ]]; then
  echo "Usage: $0 <image> <commit>"
  echo "Example: $0 swenyai/worker:v1.2.3 abc1234"
  exit 1
fi

echo "Fetching manifest for: $IMAGE"
DIGEST=$(docker manifest inspect "$IMAGE" 2>/dev/null | jq -r '.config.digest // empty')

if [[ -z "$DIGEST" ]]; then
  echo "Error: could not retrieve manifest for $IMAGE"
  echo "Make sure the image exists and you are authenticated to the registry."
  exit 1
fi

echo ""
echo "Image digest : $DIGEST"
echo "Expected commit: $COMMIT"
echo ""
echo "Verify at: https://github.com/swenyai/sweny/releases/tag/worker-$COMMIT"
echo ""
echo "The release page includes:"
echo "  - The canonical image digest for this commit"
echo "  - SBOM (Software Bill of Materials) generated by syft"
echo "  - Build provenance attestation"
echo ""
echo "To verify locally, rebuild from source and compare digests:"
echo "  git checkout $COMMIT"
echo "  cd packages/worker"
echo "  docker buildx build --platform linux/amd64 -t swenyai/worker:local ."
echo "  docker inspect swenyai/worker:local --format='{{index .RepoDigests 0}}'"
