#!/bin/bash
# Verify a sweny-worker Docker image was built from a specific git commit.
#
# Usage:
#   ./verify-build.sh <image> <commit>
#
# Example:
#   ./verify-build.sh swenyai/worker:v1.2.3 abc1234
#
# This script:
#   1. Pulls the image manifest and extracts its SHA256 digest
#   2. Prints the digest and the expected commit for manual cross-reference
#   3. Points you to the GitHub Releases attestation where the canonical mapping is published
#
# For automated verification, compare the digest against the attestation JSON
# published at https://github.com/swenyai/sweny/releases/tag/worker-<commit>

set -euo pipefail

IMAGE=${1:-}
COMMIT=${2:-}

if [[ -z "$IMAGE" || -z "$COMMIT" ]]; then
  echo "Usage: $0 <image> <commit>"
  echo "Example: $0 swenyai/worker:v1.2.3 abc1234"
  exit 1
fi

echo "Fetching manifest for: $IMAGE"
# Use `.manifests[0].digest` for multi-arch manifests (OCI index), falling back
# to `.schemaVersion` check for single-arch manifests.
# `.config.digest` is the image config hash — not the same as the image manifest
# digest that registries expose as the canonical "image digest".
MANIFEST=$(docker manifest inspect "$IMAGE" 2>/dev/null)
DIGEST=$(echo "$MANIFEST" | jq -r '
  if .manifests then
    # OCI image index (multi-arch): use the amd64 manifest digest
    (.manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest) // .manifests[0].digest
  else
    # Single-arch manifest: the digest comes from the registry — use docker inspect
    empty
  end
')

if [[ -z "$DIGEST" ]]; then
  # Single-arch image: pull and inspect to get the repo digest
  docker pull --quiet "$IMAGE" >/dev/null 2>&1 || true
  DIGEST=$(docker inspect "$IMAGE" --format='{{index .RepoDigests 0}}' 2>/dev/null | cut -d@ -f2)
fi

if [[ -z "$DIGEST" ]]; then
  echo "Error: could not retrieve manifest for $IMAGE"
  echo "Make sure the image exists and you are authenticated to the registry."
  exit 1
fi

echo ""
echo "Image digest : $DIGEST"
echo "Expected commit: $COMMIT"
echo ""
echo "Verify at: https://github.com/swenyai/sweny/releases/tag/worker-$COMMIT"
echo ""
echo "The release page includes:"
echo "  - The canonical image digest for this commit"
echo "  - SBOM (Software Bill of Materials) generated by syft"
echo "  - Build provenance attestation"
echo ""
echo "To verify locally, rebuild from source and compare digests:"
echo "  git checkout $COMMIT"
echo "  cd packages/worker"
echo "  docker buildx build --platform linux/amd64 --load -t swenyai/worker:local ."
echo "  docker inspect swenyai/worker:local --format='{{index .RepoDigests 0}}'"
echo "  # Note: for an exact manifest digest match, push to a registry first:"
echo "  docker buildx build --platform linux/amd64 --push -t <registry>/worker:local ."
echo "  docker manifest inspect <registry>/worker:local | jq -r '.manifests[0].digest'"
