import * as fs from "fs";
import type { IssueTrackingProvider, PrLinkCapable } from "@swenyai/providers/issue-tracking";
import { canLinkPr } from "@swenyai/providers/issue-tracking";
import type { SourceControlProvider } from "@swenyai/providers/source-control";
import type { CodingAgent } from "@swenyai/providers/coding-agent";
import type { StepResult, WorkflowContext } from "../../../types.js";
import type { TriageConfig } from "../types.js";
import { getStepData } from "../results.js";
import { buildPrDescriptionPrompt } from "../prompts.js";

/** Generate PR description with Claude, create PR, link to issue, update issue state. */
export async function createPr(ctx: WorkflowContext<TriageConfig>): Promise<StepResult> {
  const config = ctx.config;
  const sourceControl = ctx.providers.get<SourceControlProvider>("sourceControl");
  const issueTracker = ctx.providers.get<IssueTrackingProvider>("issueTracker");
  const codingAgent = ctx.providers.get<CodingAgent>("codingAgent");
  const issueData = getStepData(ctx, "create-issue");
  const implementData = getStepData(ctx, "implement-fix");

  // If implement-fix was skipped, we can't create a PR
  const implementResult = ctx.results.get("implement-fix");
  if (!implementResult || implementResult.status !== "success") {
    return {
      status: "skipped",
      reason: implementResult?.reason ?? "No implementation to create PR for",
    };
  }

  const issueId = issueData?.issueId ?? "";
  const issueIdentifier = issueData?.issueIdentifier ?? "";
  const issueTitle = issueData?.issueTitle ?? "";
  const issueUrl = issueData?.issueUrl ?? "";
  const branchName = implementData?.branchName ?? "";

  // -------------------------------------------------------------------------
  // 1. Generate PR description with Claude
  // -------------------------------------------------------------------------
  const prDescPrompt = buildPrDescriptionPrompt(issueIdentifier, issueUrl);
  await codingAgent.run({
    prompt: prDescPrompt,
    maxTurns: 10,
    env: { ...config.agentEnv },
  });

  // -------------------------------------------------------------------------
  // 2. Create Pull Request
  // -------------------------------------------------------------------------
  let prBody = "";
  const prDescPath = ".github/triage-analysis/pr-description.md";
  if (fs.existsSync(prDescPath)) {
    prBody = fs.readFileSync(prDescPath, "utf-8");
  } else {
    prBody = `## Automated Fix from SWEny Triage

This PR contains an automated fix for an issue identified in production logs.

**Linear Issue**: [${issueIdentifier}](${issueUrl})

> Generated by SWEny Triage`;
  }

  const prTitle = `fix(${issueIdentifier}): ${issueTitle.toLowerCase()}`;

  const pr = await sourceControl.createPullRequest({
    title: prTitle,
    body: prBody,
    head: branchName,
    base: "main",
    labels: ["agent", "triage", "needs-review"],
  });
  ctx.logger.info(`Created PR #${pr.number}: ${pr.url}`);

  // -------------------------------------------------------------------------
  // 3. Link PR to issue
  // -------------------------------------------------------------------------
  if (issueId && canLinkPr(issueTracker)) {
    try {
      await (issueTracker as IssueTrackingProvider & PrLinkCapable).linkPr(issueId, pr.url, pr.number);
      ctx.logger.info(`PR #${pr.number} linked to ${issueIdentifier}`);
    } catch (err) {
      ctx.logger.warn(`Failed to link PR to issue: ${err}`);
    }
  }

  // -------------------------------------------------------------------------
  // 4. Update issue state to Peer Review
  // -------------------------------------------------------------------------
  if (issueId) {
    try {
      await issueTracker.updateIssue(issueId, {
        stateId: config.statePeerReview,
      });
      ctx.logger.info(`Updated ${issueIdentifier} to Peer Review`);
    } catch (err) {
      ctx.logger.warn(`Failed to update issue state: ${err}`);
    }
  }

  return {
    status: "success",
    data: {
      issueIdentifier,
      issueUrl,
      prUrl: pr.url,
      prNumber: pr.number,
    },
  };
}
